### ISSUE TITLE
Provide Fedora 34 Package

### ISSUE THREAD

**Issue by reisaraujo-miguel** [bebosudo/olive-editor-rpm#2]
I tried to install this package but dnf gives me an error saying that there is no build yet:
![image](https://user-images.githubusercontent.com/58122451/123876709-2ea2ec00-d912-11eb-80d6-72705f3348de.png)

**Comment by bebosudo** [comment]
Hi, I've not been using the most recent Fedora releases, so I haven't updated this package.
I tried updating it now, but it cannot find the `qt5-devel` package in the rpmfusion repo: I suspect it has been renamed.

Feel free to fork this and open a Merge Request if you find a solution!
